mode: 'train'
data:
  scale: 4
  n_samples: 352432
  div2k:
    dataset_path: './DIV2K/'
  set5:
    dataset_path: './Set5/'
  set14:
    dataset_path: './Set14/'
  bsd100:
    dataset_path: './BSD100/'
  urban100:
    dataset_path: './URBAN100/'
  tfr_data_path: './train_NatSR_x4.tfr'
model:
  model_name: 'NatSR'
  height: 192
  width: 192
  channel: 3
  batch_size: 32
  epochs: 20000
  lr: 2e-4
  lr_decay_epochs: 10000
  lr_decay_ratio: 0.5
  loss:
    # distortion-oriented (FRSR)  : 1, 0, 0
    # perception-oriented (NatSR) : 1, 1e-3, 1e-3
    recon_weight: 1        # lambda_1
    natural_weight: 1e-3   # lambda_2
    generate_weight: 1e-3  # lambda_3
aux:
  n_gpu: 1
  seed: 2020
