mode: 'train'
data:
  n_samples: 352432
  dataset_type: 'div2k'
  div2k:
    dataset_path: './DIV2K/'
    scale: 4
    interpolation: 'bicubic'
  urban100:
    dataset_path: './Urban100/'
  set5:
    dataset_path: './Set5/'
  set14:
    dataset_path: './Set14/'
  bsd100:
    dataset_path: './BSD100/'
  tfr_data_path: './train_NatSR_x4.tfr'
model:
  model_name: 'natsr'
  use_ra: True
  adv_loss_type: 'gan'
  rec_loss_type: 'l1'
  cls_loss_type: 'bce'
  natsr:
    height: 192
    width: 192
    channel: 3
    n_feats: 64
    nb_layers: 6
    n_rep_rd_blocks: 2
    n_rd_blocks: 4
    scale: 0.1
    batch_size: 32
    epochs: 20000
    optimizer: 'adam'
    lr: 1e-4
    lr_schedule_type: 'exponential'
    lr_decay_epochs: 100000
    lr_decay_ratio: 0.1
    loss:
      # distortion-oriented (FRSR)  : 1, 0, 0
      # perception-oriented (NatSR) : 1, 1e-3, 1e-3
      recon_weight: 1        # lambda_1
      natural_weight: 1e-3   # lambda_2
      generate_weight: 1e-3  # lambda_3
  nmd:
    height: 144
    width: 144
    channel: 3
    n_feats: 64
    batch_size: 32
    epochs: 20000
    sigma: 0.1
    sigma_mul_ratio: 0.8
    alpha: 0.5
    alpha_add_ratio: 0.1
    alpha_clip: [0.0, 0.9]
    optimizer: 'adam'
    lr: 1e-4
  eps: 1e-8
checkpoint:
  gen_model_path: './gen_model.pth'
  disc_model_path: './disc_model.pth'
  nmd_model_path: './nmd_model.pth'
aux:
  n_gpu: 1
  n_threads: 8
  device: 'cuda'
  seed: 2020
